from __future__ import annotations

"""Orbit Propagation (OP) pipeline.

Consumes `od_solution.json` generated by `src.pipelines.od` and produces:
- op_ephemeris.csv  (inertial + ECEF PV)
- op_ephemeris.oem  (CCSDS OEM 2.0, inertial PV)
- op_summary.json

Typical usage
    python -m src.pipelines.op configs/case_c_od_op_only_2025.json
    python -m src.pipelines.op outputs/od_solution.json

Notes
- Cd estimation is intentionally NOT performed here. If OD estimated Cd, that
  value will be used for propagation; otherwise cd0 is used.
"""

import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Optional, Tuple

import datetime as dt

import pandas as pd

from src.orekit_bootstrap import init_orekit
from src.pipelines.ccsds_oem import OEMMeta, write_oem_from_ephem_df


def _parse_iso_utc(s: str) -> dt.datetime:
    s = s.strip()
    if s.endswith("Z"):
        s = s[:-1] + "+00:00"
    # allow no fractional seconds
    return dt.datetime.fromisoformat(s).astimezone(dt.timezone.utc)


def _load_json(path: Path) -> Dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _looks_like_od_solution(d: Dict[str, Any]) -> bool:
    return isinstance(d, dict) and "epoch_utc" in d and "state_inertial" in d and "forces" in d


def _resolve_inputs(arg_path: Path) -> Tuple[Dict[str, Any], Dict[str, Any], Path]:
    """
    Returns: (od_solution, cfg_dict, outputs_dir)

    - If arg_path is a Case-C style config, it loads outputs_dir/od_solution.json.
    - If arg_path is an od_solution.json itself, it uses that and sets outputs_dir
      to the file's parent directory.
    """
    d = _load_json(arg_path)

    if _looks_like_od_solution(d):
        od_solution = d
        cfg = {}
        outputs_dir = arg_path.parent
        return od_solution, cfg, outputs_dir

    # Otherwise treat as config
    cfg = d
    outputs_dir = Path(cfg.get("outputs_dir", "outputs"))

    od_sol_path = outputs_dir / "od_solution.json"
    if not od_sol_path.exists():
        # Try legacy name (if user kept older artifacts)
        od_sol_path = outputs_dir / "case_c_od_solution.json"
    if not od_sol_path.exists():
        raise FileNotFoundError(
            f"od_solution.json not found under outputs_dir={outputs_dir}. "
            "Run: python -m src.pipelines.od <config.json> first."
        )

    od_solution = _load_json(od_sol_path)
    return od_solution, cfg, outputs_dir


@dataclass
class OpSettings:
    time_start_utc: Optional[str] = None
    span_hours: float = 24.0
    step_s: int = 60


def _get_op_settings(cfg: Dict[str, Any]) -> OpSettings:
    op = cfg.get("op", {}) if isinstance(cfg, dict) else {}
    # allow flat keys too
    return OpSettings(
        time_start_utc=op.get("time_start_utc") or cfg.get("op_time_start_utc"),
        span_hours=float(op.get("span_hours", 24.0)),
        step_s=int(op.get("step_s", 60)),
    )


def run_op(arg_path: str) -> Dict[str, Any]:
    p = Path(arg_path)
    if not p.exists():
        raise FileNotFoundError(p)

    od_solution, cfg, out_dir = _resolve_inputs(p)
    out_dir.mkdir(parents=True, exist_ok=True)

    settings = _get_op_settings(cfg)

    # --- Init Orekit ---
    init_orekit()

    # Imports after JVM start
    from org.orekit.time import TimeScalesFactory, AbsoluteDate
    from org.orekit.frames import FramesFactory
    from org.orekit.utils import IERSConventions, Constants, PVCoordinates
    from org.hipparchus.geometry.euclidean.threed import Vector3D
    from org.orekit.orbits import CartesianOrbit, PositionAngleType
    from org.orekit.propagation import SpacecraftState
    from org.hipparchus.ode.nonstiff import DormandPrince853Integrator
    from org.orekit.propagation.numerical import NumericalPropagator
    from org.orekit.forces.gravity.potential import GravityFieldFactory
    from org.orekit.forces.gravity import HolmesFeatherstoneAttractionModel, ThirdBodyAttraction
    from org.orekit.bodies import CelestialBodyFactory, OneAxisEllipsoid
    from org.orekit.forces.drag import DragForce, IsotropicDrag
    from org.orekit.models.earth.atmosphere import SimpleExponentialAtmosphere

    utc = TimeScalesFactory.getUTC()
    inertial = FramesFactory.getEME2000()
    itrf = FramesFactory.getITRF(IERSConventions.IERS_2010, True)

    earth = OneAxisEllipsoid(
        Constants.WGS84_EARTH_EQUATORIAL_RADIUS,
        Constants.WGS84_EARTH_FLATTENING,
        itrf,
    )

    forces = od_solution["forces"]
    mass_kg = float(forces["mass_kg"])
    area_m2 = float(forces["area_m2"])
    cd0 = float(forces["cd0"])
    cd_est = od_solution.get("estimated_params", {}).get("cd", None)
    cd_used = float(cd_est) if cd_est is not None else cd0

    # Initial state
    epoch = _parse_iso_utc(str(od_solution["epoch_utc"]))
    date0 = AbsoluteDate(epoch.year, epoch.month, epoch.day,
                         epoch.hour, epoch.minute,
                         epoch.second + epoch.microsecond / 1e6, utc)

    r = od_solution["state_inertial"]["r_m"]
    v = od_solution["state_inertial"]["v_mps"]
    pv0 = PVCoordinates(
        Vector3D(float(r[0]), float(r[1]), float(r[2])),
        Vector3D(float(v[0]), float(v[1]), float(v[2])),
    )

    mu = Constants.WGS84_EARTH_MU
    orbit0 = CartesianOrbit(pv0, inertial, date0, mu)

    # Integrator / propagator
    min_step = 1.0
    max_step = float(max(1, settings.step_s))
    pos_tol = 10.0
    integrator = DormandPrince853Integrator(min_step, max_step, pos_tol, pos_tol)

    propagator = NumericalPropagator(integrator)
    propagator.setInitialState(SpacecraftState(orbit0, mass_kg))

    # Force models
    grav = GravityFieldFactory.getNormalizedProvider(int(forces["gravity_degree"]), int(forces["gravity_order"]))
    propagator.addForceModel(HolmesFeatherstoneAttractionModel(itrf, grav))

    if bool(forces.get("use_third_body", False)):
        propagator.addForceModel(ThirdBodyAttraction(CelestialBodyFactory.getSun()))
        propagator.addForceModel(ThirdBodyAttraction(CelestialBodyFactory.getMoon()))

    # Drag
    atmosphere_kind = str(forces.get("atmosphere", "SIMPLE_EXP")).upper()
    if atmosphere_kind == "SIMPLE_EXP":
        atmosphere = SimpleExponentialAtmosphere(
            earth, float(forces["rho0"]), float(forces["h0_m"]), float(forces["h_scale_m"])
        )
    else:
        atmosphere = SimpleExponentialAtmosphere(
            earth, float(forces["rho0"]), float(forces["h0_m"]), float(forces["h_scale_m"])
        )

    drag_sensitive = IsotropicDrag(area_m2, cd_used)
    propagator.addForceModel(DragForce(atmosphere, drag_sensitive))

    # Prop window
    start_dt = _parse_iso_utc(settings.time_start_utc) if settings.time_start_utc else epoch
    stop_dt = start_dt + dt.timedelta(hours=float(settings.span_hours))

    # Generate ephemeris at uniform step
    rows = []
    n_steps = int((stop_dt - start_dt).total_seconds() // settings.step_s)
    for k in range(n_steps + 1):
        ts = start_dt + dt.timedelta(seconds=k * settings.step_s)
        date = AbsoluteDate(ts.year, ts.month, ts.day, ts.hour, ts.minute,
                            ts.second + ts.microsecond / 1e6, utc)
        st = propagator.propagate(date)
        pv_i = st.getPVCoordinates()

        ri = pv_i.getPosition()
        vi = pv_i.getVelocity()

        tr = inertial.getTransformTo(itrf, date)
        pv_e = tr.transformPVCoordinates(pv_i)
        re = pv_e.getPosition()
        ve = pv_e.getVelocity()

        rows.append({
            "iso_utc": ts.strftime("%Y-%m-%dT%H:%M:%S.%fZ"),
            "x_i_m": float(ri.getX()), "y_i_m": float(ri.getY()), "z_i_m": float(ri.getZ()),
            "vx_i_mps": float(vi.getX()), "vy_i_mps": float(vi.getY()), "vz_i_mps": float(vi.getZ()),
            "x_ecef_m": float(re.getX()), "y_ecef_m": float(re.getY()), "z_ecef_m": float(re.getZ()),
            "vx_ecef_mps": float(ve.getX()), "vy_ecef_mps": float(ve.getY()), "vz_ecef_mps": float(ve.getZ()),
        })

    ephem = pd.DataFrame(rows)
    ephem_path = out_dir / "op_ephemeris.csv"
    ephem.to_csv(ephem_path, index=False, encoding="utf-8-sig")

    # OEM
    oem_path = out_dir / "op_ephemeris.oem"
    meta = OEMMeta(
        object_name=str(cfg.get("object_name", "SAT")),
        object_id=str(cfg.get("object_id", "UNKNOWN")),
        ref_frame=str(od_solution.get("frame_inertial", "EME2000")),
        originator="Difference_Drag",
    )
    write_oem_from_ephem_df(ephem, oem_path, meta)

    op_summary = {
        "status": "ok",
        "outputs_dir": str(out_dir),
        "epoch_utc": od_solution["epoch_utc"],
        "op_start_utc": start_dt.strftime("%Y-%m-%dT%H:%M:%S.%fZ"),
        "op_stop_utc": stop_dt.strftime("%Y-%m-%dT%H:%M:%S.%fZ"),
        "step_s": int(settings.step_s),
        "points": int(len(ephem)),
        "cd_used": cd_used,
        "artifacts": {
            "op_ephemeris_csv": str(ephem_path.name),
            "op_ephemeris_oem": str(oem_path.name),
            "op_summary_json": "op_summary.json",
        },
    }
    (out_dir / "op_summary.json").write_text(json.dumps(op_summary, indent=2), encoding="utf-8")

    return op_summary


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: python -m src.pipelines.op <config.json | od_solution.json>")
        raise SystemExit(2)

    summary = run_op(sys.argv[1])
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()